services:
  agilemindsui:
    image: ${DOCKER_REGISTRY-}agilemindsui
    build:
      context: .
      dockerfile: AgileMindsUI/AgileMindsUI/Dockerfile

  agilemindswebapi:
    image: ${DOCKER_REGISTRY-}agilemindswebapi
    build:
      context: .
      dockerfile: AgileMindsWebAPI/Dockerfile

  agilemindmysql:
    image: mysql:latest
    container_name: agilemindmysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: tobenamed
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Named volume
      - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql  # Bind mount for initialization script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ngrok:
    image: ngrok/ngrok:latest
    command: http https://localhost:60001  # Exposing the UI service
    ports:
      - "4040:4040"  # ngrok dashboard
    environment:
      - NGROK_AUTHTOKEN=2mcbEUfp345dyUmTJ5rMr5aty8P_7PLcTdwfkp5WzgbZH7Y1a
volumes:
  mysql_data: