services:
  agilemindsui:
    image: ${DOCKER_REGISTRY-}agilemindsui
    build:
      context: .
      dockerfile: AgileMindsUI/AgileMindsUI/Dockerfile
  agilemindswebapi:
    image: ${DOCKER_REGISTRY-}agilemindswebapi
    build:
      context: .
      dockerfile: AgileMindsWebAPI/Dockerfile
  agilemindmysql:
    image: mysql:latest
    container_name: agilemindmysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: tobenamed
    ports:
      - "3306:3306"