services:
  agilemindsui:
    image: ${DOCKER_REGISTRY-}agilemindsui
    build:
      context: .
      dockerfile: AgileMindsUI/AgileMindsUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8083:8080"
      - "60001:8081"
    volumes:
      - ./certificates:/app/certificates:ro

  agilemindswebapi:
    image: ${DOCKER_REGISTRY-}agilemindswebapi
    build:
      context: .
      dockerfile: AgileMindsWebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8082:8080"
      - "60000:8081"
    volumes:
      - ./certificates:/app/certificates:ro

  agilemindmysql:
    image: mysql:latest
    container_name: agilemindmysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: tobenamed
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Named volume
      - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql  # Bind mount for initialization script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
